package com.myspace.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label("Is this order associated with HOA?")
	private boolean isAssociatedWithHOA;
	@org.kie.api.definition.type.Label("Are you OK with the meeting?")
	private boolean isMeetingScheduled;
	@org.kie.api.definition.type.Label("Are you OK with an installation?")
	private boolean isApprovedFromHOA;

	@org.kie.api.definition.type.Label(value = "Order ID")
	private int id;

	public NewOrder() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public boolean isIsMeetingScheduled() {
		return this.isMeetingScheduled;
	}

	public void setIsMeetingScheduled(boolean isMeetingScheduled) {
		this.isMeetingScheduled = isMeetingScheduled;
	}

	public boolean isIsApprovedFromHOA() {
		return this.isApprovedFromHOA;
	}

	public void setIsApprovedFromHOA(boolean isApprovedFromHOA) {
		this.isApprovedFromHOA = isApprovedFromHOA;
	}

	public boolean isIsAssociatedWithHOA() {
		return this.isAssociatedWithHOA;
	}

	public void setIsAssociatedWithHOA(boolean isAssociatedWithHOA) {
		this.isAssociatedWithHOA = isAssociatedWithHOA;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public NewOrder(java.lang.String name, java.lang.String address,
			boolean isAssociatedWithHOA, boolean isMeetingScheduled,
			boolean isApprovedFromHOA, int id) {
		this.name = name;
		this.address = address;
		this.isAssociatedWithHOA = isAssociatedWithHOA;
		this.isMeetingScheduled = isMeetingScheduled;
		this.isApprovedFromHOA = isApprovedFromHOA;
		this.id = id;
	}

}